### ISSUE TITLE
Bot's wont start after a little bit of time

### ISSUE THREAD

**Issue by Pichulol** [RosneBurgerworks/rosnebot-setup#2]
When hosting the bots if one crashes or you shut it down it wont start backup again and will stay on "STARTING"
Only happens after the server is running for a certain time period.

**Comment by snipergaming134** [comment]
> When hosting the bots if one crashes or you shut it down it wont start backup again and will stay on "STARTING" Only happens after the server is running for a certain time period.

That's because you then have to redo the process again in bot.js if the bots crash

**Comment by snipergaming134** [comment]
Are you using Ubuntu?

**Comment by rosne-gamingyt** [comment]
issue fixed
