### ISSUE TITLE
cant run

### ISSUE THREAD

**Issue by Tira-tw** [RosneBurgerworks/rosnebot-setup#5]
~/rosnebot-setup/rosnehook-ipc-web-panel ~/rosnebot-setup
~/rosnebot-setup
Setting up micspam...
./run.sh: line 10: logs/main.log: No such file or directory
Failure: Module initialization failed
cat: /tmp/cat-webpanel-password: No such file or directory

**Comment by rosne-gamingyt** [comment]
make a folder inside rosnebot-setup called logs, then inside that make a blank file called main.log

**Comment by Tira-tw** [comment]
> make a folder inside rosnebot-setup called logs, then inside that make a blank file called main.log

![image](https://github.com/RosneBurgerworks/rosnebot-setup/assets/64715639/f282214f-ebb0-4c3f-9579-b1826098ccc5)

**Comment by boofiboi** [comment]
did you install rosnehook before rosnebot?

if yes, try running ./install_catbots in the rosnebot directory

**Comment by Tira-tw** [comment]
> 你在安裝rosnebot之前安裝了rosnehook嗎？
> 
> 如果是，請嘗試在 rosnebot 目錄中執行 ./install_catbots

~/rosnebot-setup/rosnehook-ipc-web-panel ~/rosnebot-setup
~/rosnebot-setup
Setting up micspam...
Failure: Module initialization failed
                                     internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'extend'
Require stack:
- /home/tira/rosnebot-setup/rosnehook-ipc-web-panel/cathook.js
- /home/tira/rosnebot-setup/rosnehook-ipc-web-panel/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/tira/rosnebot-setup/rosnehook-ipc-web-panel/cathook.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/tira/rosnebot-setup/rosnehook-ipc-web-panel/cathook.js',
    '/home/tira/rosnebot-setup/rosnehook-ipc-web-panel/app.js'
  ]
}
cat: /tmp/cat-webpanel-password: No such file or directory

**Comment by boofiboi** [comment]
Did you install rosnehook before running rosnebot?

**Comment by Tira-tw** [comment]
> Did you install rosnehook before running rosnebot?

I was watching this video install 
https://youtu.be/bNoTEz2_BqY?si=UpL5aMHmfLia0ixn

**Comment by boofiboi** [comment]
Did you install rosnehook before installing rosnebot.

**Comment by Tira-tw** [comment]
> Did you install rosnehook before installing rosnebot.

temprosnehook > rosnebot-setup

**Comment by boofiboi** [comment]
Try redoing the tutorial again 

cd; rm -rf temprosnehook; rm -rf rosnebot-setup

then do the steps in the tutorial again

**Comment by AssociatedWithN** [comment]
How many IQ points do you have?

**Comment by rosne-gamingyt** [comment]
> > 你在安裝rosnebot之前安裝了rosnehook嗎？
> > 如果是，請嘗試在 rosnebot 目錄中執行 ./install_catbots
> 
> ~/rosnebot-setup/rosnehook-ipc-web-panel ~/rosnebot-setup ~/rosnebot-setup Setting up micspam... Failure: Module initialization failed internal/modules/cjs/loader.js:818 throw err; ^
> 
> Error: Cannot find module 'extend' Require stack:
> 
> * /home/tira/rosnebot-setup/rosnehook-ipc-web-panel/cathook.js
> * /home/tira/rosnebot-setup/rosnehook-ipc-web-panel/app.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:667:27)
>   at Module.require (internal/modules/cjs/loader.js:887:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (/home/tira/rosnebot-setup/rosnehook-ipc-web-panel/cathook.js:3:16)
>   at Module._compile (internal/modules/cjs/loader.js:999:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>   at Module.load (internal/modules/cjs/loader.js:863:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>   at Module.require (internal/modules/cjs/loader.js:887:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/home/tira/rosnebot-setup/rosnehook-ipc-web-panel/cathook.js',
>   '/home/tira/rosnebot-setup/rosnehook-ipc-web-panel/app.js'
>   ]
>   }
>   cat: /tmp/cat-webpanel-password: No such file or directory

npm install extend

**Comment by AssociatedWithN** [comment]
I KNOW THE FIX!!!

npm install extend

Found it all by myself.
