### ISSUE TITLE
Failed to get web_session in auto-profile.py

### ISSUE THREAD

**Issue by gerundim** [RosneBurgerworks/rosnebot-setup#7]
Logging in as user #1/10 (gerundim01)...
Login status: OK (1)
Logged in as: gerundim01
Community profile: https://steamcommunity.com/profiles/76561199484389503
Changed Steam nickname to "Gerundim"
Getting web_session...
Failed to create a session. Check your authentication or network.
Done; logging out.

**Comment by pay2lose2** [comment]
This is normal, steam broke sessions which are required for profile picture changes, removal of past aliases and etc.

So far no fix besides setting pfps manually

**Comment by AssociatedWithN** [comment]
Refund, kid.
Switch back to Windows.
![h1.jpg](https://github.com/RosneBurgerworks/rosnebot-setup/assets/157900452/66c02c11-816a-4c17-8e14-e2e9a4c09d52)

Join the superior master race...

**Comment by AssociatedWithN** [comment]
(Master Race = Windows)

**Comment by AssociatedWithN** [comment]
(Master Race = Windows)

**Comment by rosne-gamingyt** [comment]
> Logging in as user #1/10 (gerundim01)... Login status: OK (1) Logged in as: gerundim01 Community profile: https://steamcommunity.com/profiles/76561199484389503 Changed Steam nickname to "Gerundim" Getting web_session... Failed to create a session. Check your authentication or network. Done; logging out.

being worked on(?)

**Comment by AssociatedWithN** [comment]
noob
